[package]
name = "ikun"
version = "1.0.0"
edition = "2021"
description = "ikun新媒体制作中心"

[lib]
name = "ikun_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "multipart"] }
base64 = "0.22"
komi-plugin = { path = "../plugins/komi" }
